______________________________________________________________________________________________________________________________________________________________________________________________
Vue
______________________________________________________________________________________________________________________________________________________________________________________________

é um framework progressivo para a construção de interfaces de usuário. Ao contrário de outros frameworks monolíticos, Vue foi projetado desde sua concepção para ser adotável incrementalmente. 
A biblioteca principal é focada exclusivamente na camada visual (view layer), sendo fácil adotar e integrar com outras bibliotecas ou projetos existentes. 
Por outro lado, Vue também é perfeitamente capaz de dar poder a sofisticadas Single-Page Applications quando usado em conjunto com ferramentas modernas e bibliotecas de apoio.

_______________________________________________________________________________________________________________________________________________________________________________________________
Framework progressivo para interfaces web

Sintaxe mais simples e próxima de HTML, CSS e JS separados

Curva de aprendizado mais fácil

Estrutura mais guiada

Ideal para projetos rápidos e equipes menores

_______________________________________________________________________________________________________________________________________________________________________________________________

Resumo rápido

React → Web

Vue → Web (mais simples)

React Native → Mobile (Android/iOS)

_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Comparação com Outros Frameworks:

React:
React e Vue compartilham muitas similaridades. Ambos:

- utilizam a abordagem de DOM virtual
- provêm componentes visuais reativos e combináveis
- mantêm o foco na biblioteca principal, com preocupações como roteamento e gerenciamento de estado global tratadas por bibliotecas companheiras.

Vue abraça as tecnologias Web clássicas e constrói em cima delas.

https://www.vuemastery.com/courses/intro-to-vue-js/vue-instance/ 




